import groovy.xml.XmlParser

allprojects  {
  apply plugin: 'maven-publish'
  group = 'org.slim3'
  version = '2.5.0-SNAPSHOT1'
}

subprojects {
  apply plugin: 'java'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(javaLanguageVersion.toInteger())
    }
  }

  tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(javaLanguageVersion.toInteger())
  }
  tasks.withType(Test).configureEach {
    systemProperty "file.encoding", "UTF-8"
  }

  repositories {
    mavenCentral()
    mavenLocal()
    maven { url = uri("https://maven.seasar.org/maven2") }
    maven { url = uri("https://maven.seasar.org/maven2-snapshot") }
  }

  publishing {
    repositories {
      def settingsXml = new XmlParser().parse(new File(System.getProperty("user.home"), ".m2/settings.xml"))
      def ghServerConfig = settingsXml.servers.server.find({ it.id.text() == "piisu.github.io" })
      maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/piisu/slim3v2")
        credentials {
          username = ghServerConfig.username.text()
          password = ghServerConfig.password.text()
        }
      }
    }
  }
}
