import groovy.xml.XmlParser

apply plugin: 'java'

description = """Slim3"""

repositories {
    mavenCentral()
    maven { url = uri("https://maven.seasar.org/maven2") }
    maven { url = uri("https://maven.seasar.org/maven2-snapshot") }
}

dependencies {
    implementation "com.google.appengine:appengine-api-1.0-sdk:${appengineApiVersion}"

    compileOnly "com.google.appengine:appengine-api-stubs:${appengineApiVersion}"
    testImplementation "com.google.appengine:appengine-api-stubs:${appengineApiVersion}"

    compileOnly "com.google.appengine:appengine-testing:${appengineApiVersion}"
    testImplementation "com.google.appengine:appengine-testing:${appengineApiVersion}"

    compileOnly "com.google.appengine:appengine-api-labs:${appengineLabsVersion}"
    testImplementation "com.google.appengine:appengine-api-labs:${appengineLabsVersion}"

    testImplementation "com.google.appengine:appengine-local-runtime:${appengineLocalRuntimeVersion}"

    compileOnly "javax.servlet:javax.servlet-api:${servletApiVersion}"
    compileOnly "javax.servlet.jsp:javax.servlet.jsp-api:${jspApiVersion}"

    compileOnly "junit:junit:${junitVersion}"
    testImplementation "junit:junit:${junitVersion}"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = 'slim3'
            version = project.version
            from components.java
        }
    }

    repositories {
        def settingsXml = new XmlParser().parse(new File(System.getProperty("user.home"), ".m2/settings.xml"))
        def ghServerConfig = settingsXml.servers.server.find({ it.id.text() == "piisu.github.io" })
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/piisu/slim3v2")
            credentials {
                username = ghServerConfig.username.text()
                password = ghServerConfig.password.text()
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }

}
