apply plugin: 'java'

description = """slim3-gen-jsr269"""

repositories {
    mavenCentral()
    maven { url = uri("https://maven.seasar.org/maven2") }
    maven { url = uri("https://maven.seasar.org/maven2-snapshot") }
}

dependencies {
    implementation "org.apache.ant:ant:${antVersion}"
    implementation project(":slim3")
    testImplementation "com.google.appengine:appengine-api-1.0-sdk:${appengineApiVersion}"
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.seasar.aptina:aptina-commons:1.0.0"
    testImplementation "org.seasar.aptina:aptina-unit:1.0.0"
}

publishing {
  publications {
    maven(MavenPublication) {
      groupId = project.group
      artifactId = 'slim3-gen-jsr269'
      version = project.version
      from components.java
    }
  }
}
